version: '3.8'

services:
  order_service:
    build: .
    container_name: "comment_response_microservice"
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_REGION_NAME=
      - FLASK_APP=application
